server:
  port: 1919
 
spring:
  application: 
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: PATIENT-SERVICE
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/patients/**
            - id: CLINICAL-SERVICE
              uri: lb://CLINICAL-SERVICE
              predicates:
                - Path=/clinical/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry:  true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
